export interface TestMasterObj{
    testId:number;
    userId:number;
    modifiedBy:number;
    LabId:number;
    department:string;
    testName:string;
    testGender:string;
    testCode:string;
    testCost:string;
    sampleType:string;
    remark:string;
    testType:string;
    testTableDataDTOList:[{ 
        entityId:number;
        sr_no:number;
        field_type:String;
        field_name:String;
        sub_field:String;
        data_type:String;
        unit:String;
        range:String;
        range_to:String;
        opertaion:String;
        operation_value:String;
        selected_options:[];
        apply_formula:String;
        formula:String;
        subFieldDataList:[{ 
            subFieldId:number,
            sr_no:number,
            field_type:String,
            field_name:String,
            sub_field:String,
            data_type:String,
            unit:String,
            range:String,
            range_to:String,
            opertaion:String,
            operation_value:String,
            selected_options:[],
            apply_formula:String,
            formula:String,
        }]
    }];
}